apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jf8fhq0wx-java-quarkus
  janus-idp.io/tekton: jf8fhq0wx-java-quarkus
  backstage.io/kubernetes-id: jf8fhq0wx-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jf8fhq0wx-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
